# Generated by Django 4.0.2 on 2022-02-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_comment_user_alter_donation_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default='None/no-img.jpg', upload_to='images/'),
        ),
    ]
