# Generated by Django 4.0.1 on 2022-02-06 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_donation_rename_created_projects_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='categorie',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='amountMoney',
        ),
    ]
