# Generated by Django 4.0.1 on 2022-02-06 20:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0007_rename_categorie_projects_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='reportcomment',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='reportcomment',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='reportproject',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='reportproject',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
