# Generated by Django 4.0.2 on 2022-02-08 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_rename_projects_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageproject',
            name='image',
            field=models.ImageField(default='None/no-img.jpg', upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='ReportComment',
        ),
    ]
