# Generated by Django 4.0.2 on 2022-02-08 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdFunding', '0008_myuser_is_active_alter_myuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profile_picture',
            field=models.ImageField(default='images/images.jpeg', upload_to='images/'),
        ),
    ]
